#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
go test -race ./...
go vet ./...
(cd frontend && npm ci --ignore-scripts && npm test)
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build ./...
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go vet ./...
printf '\nCore/TypeScript checks completed. The nested Wails module and real-account tests are separate.\n'
